config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :posts do
    resources :comments, only: [:create, :edit, :update, :destroy] 
  end

  root 'posts#index'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post, class_name: 'Post', required: true 
  validates :body, presence: true
end

app/models/post.rb
class Post < ApplicationRecord
  has_many :comments, class_name: 'Comment',  dependent: :destroy
  validates :title, presence: true, length: { minimum: 3, message: 'Too short to post!'}
  validates :body, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  def create
    comment = post.comments.new(comment_params)
    if comment.save
      flash[:success] = 'Commentレコードの作成に成功しました'
    else
      flash[:error] = 'Commentレコードの作成に失敗しました'
    end
    redirect_to post_path(@post)
  end
  
  def edit;
  end

  def update
    if comment.update(comment_params)
      redirect_to post_path(@post), flash: {success: 'Commentレコードの更新に成功しました' }
    else
      flash.now[:error] = 'Commentレコードの更新に失敗しました'
      render :edit
    end
  end

  def destroy
    if comment.destroy
      flash[:success] = 'Commentレコードの削除に成功しました'
    else
      flash[:error] = 'Commentレコードの削除に失敗しました'
    end
    redirect_to post_path(@post)
  end
  
  private

  def comment_params
    params.require(:comment).permit(:body)
  end

  def post
    @post ||= Post.find(params[:post_id])
  end

  def comment
    @comment ||= post.comments.find(params[:id])
  end
  helper_method :post, :comment


end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

  def index
    @posts = Post.all.order(created_at: 'desc')
  end

  def show
    @comment = post.comments.new
  end

  def new
    @post = Post.new
  end

  def create
    # render plain: params[:post].inspect
    # save
    @post = Post.new(post_params)
    if @post.save
      # redirect
      redirect_to posts_path, flash: {success: 'Postレコードの保存に成功しました'}
    else
      flash.now[:error] = 'Postレコードの保存に失敗しました'
      render :new
    end
  end

  def edit
    post
  end

  def update
    if post.update(post_params)
      redirect_to posts_path, flash: {success: 'Postレコードの更新に成功しました' }
    else
      flash.now[:error] = 'Postレコードの更新に失敗しました'
      render :edit
    end
  end
  
  def destroy
    if post.destroy
      flash[:success] = 'Postレコードの削除に成功しました'
    else
      flash[:error] = 'Postレコードの削除に失敗しました'
    end      
    redirect_to posts_path
  end

  private

  def post_params
    params.require(:post).permit(:title, :body)
  end

  def post
    @post ||= Post.find(params[:id])
  end  
  helper_method :post

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/comments/_form.html.erb
<%= form_for [post, comment] do |f| %>
  <p>
    <%= f.text_area :body, placeholder: 'enter comments' %>
    <% if comment.errors.messages[:body].any? %>
      <% comment.errors.messages.each do |message| %>
        <span class="error">
          <%= message %>
        </span>
      <% end %>
    <% end %>
  </p>
  <p>
    <%= f.submit %>
  </p>
  <p>
    <%= link_to '[Back]', post_path(post) %>
  </p>

<% end %>

app/views/comments/edit.html.erb
<h2> Edit Comment </h2>
<%= render 'form' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Myblog</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% flash.each do |message_type, message| %>
      <%= message %>
    <% end %>
    <div class = "container"> 
    <h1><%= link_to image_tag( 'logo.png', class: 'logo'), root_path %></h1>
      <%= yield %>
    </div>
  </body>
</html>

app/views/posts/_form.html.erb
<%= form_for post do |f| %>
  <p>
    <%= f.text_field :title, placeholder: 'enter title' %>
    <% if post.errors.messages[:title].any? %>
      <% post.errors.messages.each do |message| %>
        <span class="error">
          <%= message %>
        </span>
      <% end %>
    <% end %>
  </p>
  <p>
    <%= f.text_area :body, placeholder: 'enter body text' %>
    <% if post.errors.messages[:body].any? %>
      <% post.errors.messages.each do |message| %>
        <span class="error">
          <%= message %>
        </span>
      <% end %>
    <% end %>
  </p>
  <p>
    <%= f.submit %>
  </p>
  <p>
    <%= link_to '[Back]', posts_path %>
  </p>

<% end %>

app/views/posts/edit.html.erb
<h2> Edit Post </h2>
<%= render 'form', locals: { post: post } %>

app/views/posts/index.html.erb
<h2> 
  <%= link_to 'Add New', new_post_path, class: 'header-menu' %>
  My Posts 
</h2>
<ul>
  <% @posts.each do |post|%>
    <li>
      <%= link_to post.title, post_path(post)%>
      <%= link_to '[Edit]', edit_post_path(post), class: 'command'%>
      <%= link_to '[x]', 
      post_path(post), 
      method: :delete, 
      class: 'command',
      data: {confirm: 'Sure?'} %>
    </li>
  <% end %>
</ul>

app/views/posts/new.html.erb
<h2> Add New Post </h2>
<%= render 'form', locals: { post: @post } %>

app/views/posts/show.html.erb
<h2><%= post.title %></h2>
<p><%= simple_format post.body %></p>

<h3>Comments<h3>
<% if post.comments.any? %>
  <% post.comments.each do |comment| %>
    <% if comment.id != nil %>
      <li>
        <%= comment.body %>
        <%= link_to '[Edit]', edit_post_comment_path(post, comment), class: 'command' %>
        <%= link_to '[x]', 
          post_comment_path(post, comment), 
          method: :delete, 
          class: 'command',
          data: {confirm: 'Sure?'} %>
      </li>
    <% end %>
  <% end %>
<% end %>
<%= form_for ([post, @comment]) do |f| %>
  <p>
    <%= f.text_field :body %>
  </p>
  <p>
    <%= f.submit %>
  </p>
  <p>
    <%= link_to '[Back]', posts_path %>
  </p>
<% end %>